### ISSUE TITLE
It would be nicer if react-simple-checkbox has a check and uncheck delay controls.

### ISSUE THREAD

**Issue by sridummy** [Opsolem/react-simple-checkbox#1]

**Comment by Opsolem** [comment]
Hi, thanks for your issue.
Should the delay apply only for the animation or also for the onChange event ?

**Comment by sridummy** [comment]
animation. also little bit padding is needed for checkmark.

**Comment by pabloregis** [comment]
props for the animation speed would be great

**Comment by Opsolem** [comment]
Hi, sorry for late answer, i did not have as many time as i wanted to work on this project. Be sure i'll take a look to add these props as soon as possible

**Comment by Opsolem** [comment]
Hi, I made some updates trying to implement your suggestions. Could you give a try to the latest version (1.3.0) ?
