### ISSUE TITLE
Color state not respecting color props

### ISSUE THREAD

**Issue by hillc5** [Opsolem/react-simple-checkbox#2]
I'm rendering out several Checkbox components as row selectors, with a Select-All Checkbox above.  Suddenly (within the last week) I'm seeing the Checkbox state not respecting the color property when it is passed in.

<img width="945" alt="Screen Shot 2019-06-10 at 4 18 14 PM" src="https://user-images.githubusercontent.com/3486065/59233060-c4d50f80-8b9b-11e9-9272-8b1837d3c306.png">

On the row Checkboxes, the color value is conditional, but I've not had a problem with that in the past.

I was initially running v1.1.1, but have upgraded to 1.2.1 and the problem is still persisting.

Any help is appreciated, thanks

**Comment by hillc5** [comment]
Scratch the bit about the bug being in 1.1.1, 1.1.1 works correctly.  It looks like its in 1.2.1 and correlates with this commit: 

https://github.com/Opsolem/react-simple-checkbox/commit/ca9649faefeeb50ecdf39bff5cc3ff59e4e41876#diff-53ec23c12f0be4a531493b620d388b28R7

**Comment by Opsolem** [comment]
Hi, thanks for your issue. I'll take a look a soon as possible.

**Comment by Opsolem** [comment]
Hi, I made some update, including the colors handling. Could you give a try to the version 1.3.0 ?
