### ISSUE TITLE
onChange fires twice

### ISSUE THREAD

**Issue by Eggsix** [Opsolem/react-simple-checkbox#4]
This is usually the case when the onChange is appended to the onClick and onChange handler.
I wanted to open a pull request but I don't have access.

**Comment by Opsolem** [comment]
I'm not really sure to understand the case you are describing. Can you provide an example ?

**Comment by Eggsix** [comment]
<img width="326" alt="Screen Shot 2020-02-06 at 3 13 24 PM" src="https://user-images.githubusercontent.com/9501009/73986752-4891f800-48f3-11ea-9de7-3a34258b1c8f.png">

Since you have the onChange handler being called on both onClick and onChange. This is causing the callback to fire twice. So when I set a state to true it immediately sets it back to false.

**Comment by Eggsix** [comment]
Sorry, I'm not so sure anymore but it seems like the onChange handler fires twice. Whenever I set something to true it immediately sets it back to false.
<img width="374" alt="Screen Shot 2020-02-06 at 3 51 34 PM" src="https://user-images.githubusercontent.com/9501009/73988950-12f00d80-48f9-11ea-8db9-ffd195c4da50.png">

**Comment by Eggsix** [comment]
Sorry nevermind
