### ISSUE TITLE
Can't use ref

### ISSUE THREAD

**Issue by pedro-lb** [Opsolem/react-simple-checkbox#5]
We can't use `useRef` since this component doesn't receive and pass a ref forward.

One solution to this would be to wrap the component in `React.forwardRef` and passing down the ref to the input.

I'll be working on this later.

**Comment by pedro-lb** [comment]
I've opened a pull request to fix this:

https://github.com/Opsolem/react-simple-checkbox/pull/6

**Comment by Opsolem** [comment]
#6
