### ISSUE TITLE
Could not find a declaration file for module 'react-simple-checkbox'.

### ISSUE THREAD

**Issue by shehan-jay** [Opsolem/react-simple-checkbox#9]
Could not find a declaration file for module 'react-simple-checkbox'. 
'node_modules/react-simple-checkbox/dist/bundle.js' implicitly has an 'any' type.
  Try `npm install @types/react-simple-checkbox` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-simple-checkbox';`ts(7016)

**Comment by Opsolem** [comment]
#8
